spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:crud_prac;NON_KEYWORDS=USER
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false
  sql:
    init:
      mode: embedded


